DROP TABLE IF EXISTS `tbl_suket_nikah`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_suket_nikah` (
  `id_surat` int(11) NOT NULL AUTO_INCREMENT,
  `no_urut` varchar(5) DEFAULT NULL,
  `no_surat` varchar(30) DEFAULT NULL,
  `id_penduduk` int(11) DEFAULT NULL,
  `status_penduduk` varchar(10) DEFAULT NULL,
  `nik_suami` varchar(20) DEFAULT NULL,
  `nama_suami` varchar(100) DEFAULT NULL,
  `bin_suami` varchar(100) DEFAULT NULL,
  `pekerjaan_suami` int(11) DEFAULT NULL,
  `status_nikah_suami` varchar(10) DEFAULT NULL,
  `tmp_lahir_suami` varchar(50) DEFAULT NULL,
  `tgl_lahir_suami` date DEFAULT NULL,
  `warga_negara_suami` varchar(10) DEFAULT NULL,
  `agama_suami` int(11) DEFAULT NULL,
  `alamat_suami` varchar(100) DEFAULT NULL,
  `nik_istri` varchar(20) DEFAULT NULL,
  `nama_istri` varchar(100) DEFAULT NULL,
  `bin_istri` varchar(100) DEFAULT NULL,
  `pekerjaan_istri` int(11) DEFAULT NULL,
  `status_nikah_istri` varchar(10) DEFAULT NULL,
  `tmp_lahir_istri` varchar(50) DEFAULT NULL,
  `tgl_lahir_istri` date DEFAULT NULL,
  `warga_negara_istri` varchar(10) DEFAULT NULL,
  `agama_istri` int(11) DEFAULT NULL,
  `alamat_istri` varchar(100) DEFAULT NULL,
  `id_ayah` int(11) DEFAULT NULL,
  `id_ibu` int(11) DEFAULT NULL,
  `bin_ayah` varchar(100) DEFAULT NULL,
  `bin_ibu` varchar(100) DEFAULT NULL,
  `nama_ibu` varchar(100) DEFAULT NULL,
  `nik_ibu` varchar(100) DEFAULT NULL,
  `tmp_lahir_ibu` varchar(100) DEFAULT NULL,
  `warga_negara_ibu` varchar(100) DEFAULT NULL,
  `agama_ibu` varchar(100) DEFAULT NULL,
  `dusun_ibu` varchar(100) DEFAULT NULL,
  `pekerjaan_ibu` varchar(100) DEFAULT NULL,
  `tgl_lahir_ibu` date DEFAULT NULL,
  `alamat_ibu` varchar(100) DEFAULT NULL,
  `nama_ayah` varchar(100) DEFAULT NULL,
  `nik_ayah` varchar(100) DEFAULT NULL,
  `tmp_lahir_ayah` varchar(100) DEFAULT NULL,
  `warga_negara_ayah` varchar(100) DEFAULT NULL,
  `agama_ayah` varchar(100) DEFAULT NULL,
  `dusun_ayah` varchar(100) DEFAULT NULL,
  `pekerjaan_ayah` varchar(100) DEFAULT NULL,
  `tgl_lahir_ayah` date DEFAULT NULL,
  `alamat_ayah` varchar(100) DEFAULT NULL,
  `status_tte` int(2) DEFAULT NULL,
  `id_dokumen` int(11) DEFAULT NULL,
  `tgl_input` datetime DEFAULT NULL,
  `id_pejabat` int(11) DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id_surat`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;